{{ config(
    schema='GOLD',
    materialized='table'
) }}

SELECT
    DELIVERY_PARTNER,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    ROUND(AVG(DISTANCE_KM), 2) AS AVG_DISTANCE_KM,
    ROUND(AVG(PREP_TIME_MIN), 2) AS AVG_PREP_TIME_MIN,
    ROUND(AVG(DELIVERY_TIME_MIN), 2) AS AVG_DELIVERY_TIME_MIN,
    ROUND(AVG(TOTAL_DELIVERY_TIME_MIN), 2) AS AVG_TOTAL_DELIVERY_TIME_MIN
FROM {{ ref('fact_orders') }}
WHERE DELIVERY_PARTNER <> 'NOT_AVAILABLE'
GROUP BY DELIVERY_PARTNER
ORDER BY AVG_TOTAL_DELIVERY_TIME_MIN