{{ config(
    schema='GOLD',
    materialized='table'
) }}

SELECT
    ORDER_DATE,
    SUM(NET_AMOUNT) AS TOTAL_REVENUE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QTY) AS TOTAL_ITEMS_SOLD
FROM {{ ref('fact_orders') }}
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE