{{ config(
    schema='SILVER',
    materialized='table'
) }}

SELECT
    MENU_ITEM_ID,
    TRIM(ITEM_NAME) AS ITEM_NAME,
    UPPER(TRIM(ITEM_TYPE)) AS ITEM_TYPE,
    UPPER(TRIM(CUISINE)) AS CUISINE,
    UPPER(TRIM(DIET_TYPE)) AS DIET_TYPE,
    LIST_PRICE,
    UPPER(TRIM(STATUS)) AS STATUS,
    UPDATED_AT
FROM {{ source('bronze', 'BRONZE_MENU_ITEMS') }}