{{ config(
    schema='SILVER',
    materialized='table'
) }}

SELECT
    RESTAURANT_ID,
    TRIM(RESTAURANT_NAME) AS RESTAURANT_NAME,
    UPPER(TRIM(REGION)) AS REGION,
    TRIM(CITY) AS CITY,
    TRIM(STATE) AS STATE,
    TRIM(COUNTRY) AS COUNTRY,
    OPEN_DATE,
    TRIM(SERVICE_MODES) AS SERVICE_MODES,
    UPPER(TRIM(STATUS)) AS STATUS
FROM {{ source('bronze', 'BRONZE_LOCATIONS') }}